[package]
name = "pwasm-toy-ballot"
version = "0.1.0"
authors = ["zeroqn@users.noreply.github.com"]

[dependencies]
pwasm-std = "0.7"
pwasm-ethereum = "0.4"
pwasm-abi = "0.1"
pwasm-abi-derive = "0.1"

[dependencies.bigint]
version = "4"
default-features = false

[dependencies.parity-hash]
version = "1"
default-features = false

[dev-dependencies.pwasm-test]
git = "https://github.com/paritytech/pwasm-test"
default-features = false

[lib]
crate-type = ["cdylib"]

[features]
std = ["pwasm-std/std", "pwasm-ethereum/std", "pwasm-test/std"]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
